In [1]:
%pip install pandas

Requirement already satisfied: pandas in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

triplets = pd.read_csv(
    "../data/train_triplets.txt",
    sep="\t",
    header=None,
    names=["user_id", "song_id", "play_count"]
)

print(triplets.shape)

print("Users :", triplets["user_id"].nunique())
print("Songs :", triplets["song_id"].nunique())

print("Duplicate rows :", triplets.duplicated().sum())

(48373586, 3)
Users : 1019318
Songs : 384546
Duplicate rows : 0

In [3]:
genres = pd.read_csv(
    "../data/p02_msd_tagtraum_cd2.cls",
    sep="\t",
    comment="#",
    header=None,
    names=["track_id", "major_genre", "minor_genre"]
)

genres.head()

             track_id major_genre minor_genre
0  TRAAAAK128F9318786        Rock         NaN
1  TRAAAAW128F429D538         Rap         NaN
2  TRAAABD128F429CF47        Rock         RnB
3  TRAAADJ128F4287B47        Rock         NaN
4  TRAAADZ128F9348C2E       Latin         NaN

In [4]:
tracks = pd.read_csv(
    "../data/p02_unique_tracks.txt",
    sep="<SEP>",
    header=None,
    names=["track_id", "song_id", "artist", "title"]
)

/var/folders/_v/_6fv48812s7dnx3s4tvhd4hr0000gp/T/ipykernel_38116/897767265.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  tracks = pd.read_csv(

In [5]:
print("triplets : ",triplets.shape)
print("triplets : ",tracks.shape)
print("triplets : ",genres.shape)

songs = triplets.merge(
    tracks,
    on="song_id",
    how="left"
)

songs.isnull().sum()

songs = songs.merge(
    genres,
    on="track_id",
    how="left"
)

songs.head()

triplets :  (48373586, 3)
triplets :  (1000000, 4)
triplets :  (280831, 3)

,user_id,song_id,play_count,track_id,artist,title,major_genre,minor_genre
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1,TRIQAUQ128F42435AD,Jack Johnson,The Cove,Rock,Folk
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAPDEY12A81C210A9,1,TRIRLYL128F42539D1,Billy Preston,Nothing from Nothing,RnB,NaN
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2,TRMHBXZ128F4238406,Paco De Lucia,Entre Dos Aguas,Electronic,Metal
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFNSP12AF72A0E22,1,TRYQMNI128F147C1C7,Josh Rouse,Under Cold Blue Stars,Rock,NaN
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFOVM12A58A7D494,1,TRAHZNE128F9341B86,The Dead 60s,Riot Radio (Soundtrack Version),NaN,NaN

In [6]:
from importlib import reload
import Myspotify

reload(Myspotify)

from Myspotify import MySpotify

myspotify = MySpotify(songs)
top250 = myspotify.top_250()
top250.to_csv("../data/Top_250_track.csv")
print("--------------- TOP 250 TRACK SONGS ---------------")
print(top250)

--------------- TOP 250 TRACK SONGS ---------------
                                                artist  \
1                                        Dwight Yoakam
2                                                Björk
3                                        Kings Of Leon
4                                             Harmonia
5    Barry Tuckwell/Academy of St Martin-in-the-Fie...
..                                                 ...
246                                          Lady GaGa
247                               Sonny Boy Williamson
248                                            Nirvana
249                                    Franz Ferdinand
250                                              Cameo

                                                 title  total_play_count
1                                       You're The One            726885
2                                                 Undo            648239
3                                              Revelry            527893
4                                        Sehr kosmisch            425463
5    Horn Concerto No. 4 in E flat K495: II. Romanc...            389880
..                                                 ...               ...
246                                            Monster             37957
247                             Don't Start Me Talkin'             37942
248                                    Come As You Are             37653
249                                        Take Me Out             37541
250                                           Word Up!             37341

[250 rows x 3 columns]

In [7]:
myspotify.top_100_by_genre("Metal")

                      artist                title  total_play_count
1                  Metallica    Master Of Puppets             98667
2    Five Finger Death Punch          Bad Company             42348
3                  Nevermore            Matricide             33607
4                  Metallica   The Unforgiven III             22048
5               Apocalyptica      Refuse / Resist             17099
..                       ...                  ...               ...
96   Five Finger Death Punch       White Knuckles              3526
97          Job For A Cowboy   Martyrdom Unsealed              3499
98                    Danzig     It's Coming Down              3484
99                 Metallica  The Ecstasy Of Gold              3425
100            Parkway Drive              Carrion              3399

[100 rows x 3 columns]

In [8]:
# 50 songs about love, 50 songs about war, 50 songs about happiness,
#  50 songs about loneliness, 50 songs about money. Content-based approach.

lyrics_df, vocabulary = myspotify.load_mxm_dataset("../data/mxm_dataset_train.txt")

lyrics_df.head()

,track_id,mxm_track_id,word_counts
0,TRAAAAV128F421A322,4623710,"{'i': 6, 'the': 4, 'you': 2, 'to': 2, 'and': 5..."
1,TRAAABD128F429CF47,6477168,"{'i': 10, 'you': 17, 'to': 8, 'and': 2, 'a': 2..."
2,TRAAAED128E0783FAB,2516445,"{'i': 28, 'the': 15, 'you': 2, 'to': 12, 'and'..."
3,TRAAAEF128F4273421,3759847,"{'i': 5, 'the': 4, 'you': 3, 'to': 2, 'and': 1..."
4,TRAAAEW128F42930C0,3783760,"{'i': 4, 'to': 5, 'and': 7, 'a': 2, 'me': 4, '..."

In [9]:
spotify = MySpotify(songs, lyrics_df)
spotify.collections("love")
spotify.collections("war")
spotify.collections("happiness")
spotify.collections("loneliness")
spotify.collections("money")

,artist,title,keyword_count,total_play_count
1,Dilated Peoples,Trade Money,101,108
2,50 Cent,I Get Money,82,6140
3,Clipse,Dirty Money,79,30
4,Hot Action Cop,Doom Boom(album/edited version),71,42
5,Zion,Money,59,2
6,Gorilla Zoe,Money Man (Explicit Album Version),51,252
7,David Wilcox,Blood Money,49,26
8,Extreme,Money (In God We Trust),42,162
9,Girls Aloud,Money,38,91
10,Rick Ross / EbonyLove,Money Make Me Come,37,871
11,Joell Ortiz,Money Makes The World Go Round,37,22
12,Squirrel,Get Money,37,5
13,Van Zant,It's Only Money,33,44
14,YoungBloodZ,It's The Money/Fake ID Interlude,33,20
15,Gorillaz,Re-Hash,32,2884
16,Liberty X,Dirty Cash,31,25
17,Jesca Hoop,Money,29,206
18,Fabolous / Swizz Beatz,Return Of The Hustle,29,176
19,Hayseed Dixie,Money Talks,29,18
20,The Beatnuts,Watch Out Now,27,228
21,Mase,Money Comes And Goes (Album Version),27,152
22,Bruce Springsteen,Pay Me My Money Down,26,1299
23,Vita Chambers,Young Money,26,162
24,Tenacious D,Double Team,26,21
25,Rasheeda,Type of Gurl,26,7
26,Clipse,Door Man,25,56
27,Tapes n Tapes,The Dirty Dirty,24,212
28,Juelz Santana / Cam'Ron,Kill 'Em,24,152
29,Jamie T,If You Got The Money (Radio Edit),24,25
30,Maroon 5 / Cross,If I Never See Your Face Again,23,1233
31,Karan Casey,Another Day,23,139
32,Gang Of Four,Life_ It's A Shame,23,33
33,Kate Ryan,Another Day,23,22
34,D.A.D.,Makin' Fun of Money (LP Version),23,9
35,Eurythmics,Missionary Man,22,277
36,Jay-Z / JD,Money Ain't A Thang,21,3652
37,Supergrass,Grace,21,560
38,Lady GaGa,Money Honey,21,249
39,MIMS,Makin' Money,21,127
40,Steel Pulse,Money,21,36
41,At Vance,Money_ Money,21,33
42,Missy Elliott,Mommy (Amended Album Version w/ Mommy Interlude),20,354
43,Potluck,Money Makes the World Go Round,20,234
44,Roots Manuva,Too Cold,20,203
45,Nil Lara,Money Makes The Monkey Dance,20,58
46,EPMD,House Party,20,24
47,Big Tymers,Big Money Heavyweight,20,19
48,Daryl Hall,Money Changes Everything,20,9
49,Stevie V,Dirty Cash,19,521
50,Paul Hardcastle,Just For Money,19,310

In [10]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /Users/fouaourikt/Desktop/Slot_Projects/-Myspotify/.venv/lib/python3.12/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [11]:
spotify.train_test_split()

Train: (39731622, 8)
Test : (9932906, 8)

In [12]:
spotify.build_user_item_matrix()

(1019318, 376934)

In [13]:
spotify.fit_user_model()
print("User model trained successfully.")

User model trained successfully.

In [14]:
user = songs["user_id"].iloc[0]

spotify.similar_users(user)

(array(['c61195c4297daa4ed1d06b4893fe27071a25efc3',
        'aec93fa21e2b44c9e4cf09372c92e1d8a9094728',
        '06f1b498d68b2306f01a747841ec4bfe4f806fea',
        '9a71f75ae2c40aa6078a920a06f09e79b0645d45',
        'f96b43875aad36ecd60113ce3b9dc0d363dec3c7',
        'e90b9e0edced063b0286d62279fa0bc55b389649',
        '2159be780154f12361525f06a7df42e89883056c',
        '185e9733ca125819ef207bbe88605f032665db3d',
        '713bf1827e0464541d5eeba84889b2aa79d16907',
        '8798b9df874cdb0e65aed28deebff0801f8622e2'], dtype=object),
 array([0.4434545 , 0.41988635, 0.40478158, 0.4038893 , 0.39677644,
        0.39469135, 0.3938769 , 0.3907019 , 0.37603474, 0.37503582],
       dtype=float32))

In [15]:
user = songs["user_id"].iloc[0]

spotify.recommend_for_user(user)

,song_id,artist,title,score
0,SONRTKV12A6D4FBCB2,Furthermore,We Need To Talk (She And I Album Version),7.557954
1,SOIFGCB12A8C134160,Feist,Mushaboom,5.917112
2,SOWGZFG12A8151AF41,Jack Johnson,Monsoon,5.648226
3,SOSXUCI12A8C130984,Jack Johnson / G. Love,Rainbow,4.341605
4,SOOPWIL12AF72A3A3F,Hawk Nelson,California,4.198864
5,SOIUIDA12A8C13339B,Vibracathedral Orchestra,Untitled 4,3.967764
6,SOKJEPS12A8C1422A0,"Damian ""Jr. Gong"" Marley",Party Time,3.946913
7,SOMVIOV12A6D4F719A,ARRESTED DEVELOPMENT,Tennessee (Pirate Radio Mix),3.946913
8,SOAKIMP12A8C130995,Jack Johnson,The Cove,3.132174
9,SORIAPG12AC46887CF,Federico Aubele,Este amor,2.777435

In [ ]:
spotify.precision_at_k()